import type { PlanetData } from "./planet"

export const PLANETS: PlanetData[] = [
  {
    id: "skills",
    name: "Skills",
    description: "Technical expertise & capabilities",
    color: "#00c8dc",
    emissive: "#006878",
    size: 1.5,
    orbitRadius: 12,
    orbitSpeed: 0.15,
    hasRing: false,
    hasAtmosphere: true,
    atmosphereColor: "#00c8dc",
    moons: 1,
    tilt: 0.2,
    isSkillsPlanet: true,
    skills: [
      { name: "React / Next.js", years: 5, confidence: 95, production: true },
      { name: "TypeScript", years: 4, confidence: 92, production: true },
      { name: "Three.js / WebGL", years: 3, confidence: 85, production: true },
      { name: "Node.js / Python", years: 5, confidence: 90, production: true },
      { name: "Cloud (AWS/GCP)", years: 4, confidence: 80, production: true },
      { name: "UI/UX Design", years: 3, confidence: 75, production: false },
    ],
    content: {
      title: "SKILLS MATRIX",
      items: [
        "React.js, Node.js",
        "HTML5, CSS3, Vanilla JS",
        "Python, C, C++",
        "Figma, Da Vinci Resolve",
        "UI/UX Design & GenAI Tools",
      ],
    },
  },
  {
    id: "projects",
    name: "Projects",
    description: "Featured missions & deployments",
    color: "#ff6600",
    emissive: "#993300",
    size: 2,
    orbitRadius: 20,
    orbitSpeed: 0.1,
    hasRing: true,
    ringColor: "#ff8844",
    hasAtmosphere: true,
    atmosphereColor: "#ff6600",
    moons: 2,
    tilt: 0.15,
    content: {
      title: "PROJECT MISSIONS LOG",
      items: [
        "Signetic - ASL Sign Language Recognition TFJs and Medipipe",
        "SmartTrafficML - ASL Sign Language Recognition TFJs and Medipipe",
        "Truthchain- A Real-Time Traffic Congestion Predictor",
        "Spaceship game - HTML5, JS based space shooter game",
        "CliniSense - AI-Powered Clinical Note Summarizer & Diagnostic Assistant ",
        "Python News Teller - Real-time news support with TTS",
        "Personal Portfolio - A simple portfolio website for Anurag Pandit",
      ],
    },
  },
  {
    id: "experience",
    name: "Experience",
    description: "Career trajectory & history",
    color: "#8ecae6",
    emissive: "#4a6a7a",
    size: 1.2,
    orbitRadius: 28,
    orbitSpeed: 0.07,
    hasRing: false,
    hasAtmosphere: true,
    atmosphereColor: "#8ecae6",
    moons: 0,
    tilt: 0.35,
    content: {
      title: "ASTRO CAREER TRAJECTORY",
      items: [
        "Creative Lead @ Google Developer Groups on campus IIIT Kalyani",
        "Core Team Member @ CodeCubes - CP Club of IIIT Kalyani",
        "Core Team Member @ IEEE SB IIIT Kalyani ",
      ],
    },
  },
  {
    id: "achievements",
    name: "Achievements",
    description: "Awards & milestones",
    color: "#ffcc00",
    emissive: "#997700",
    size: 1,
    orbitRadius: 35,
    orbitSpeed: 0.05,
    hasRing: true,
    ringColor: "#ffdd44",
    hasAtmosphere: false,
    moons: 3,
    tilt: 0.5,
    content: {
      title: "COMMENDATIONS",
      items: [
        "Top10 at InnovateX Hackathon 2026 ",
        "2nd Runner-up at Udbhav Inter college Hackathon IIIT Kalyani",
        "Participant at Botball Competition 2025",
        "Best Boy award at Saraswati Vidyalaya  - Xth grade 2022",
      ],
    },
  },
  
  {
    id: "education",
    name: "Education",
    description: "Knowledge acquisition stations",
    color: "#26c6da",
    emissive: "#00838f",
    size: 0.9,
    orbitRadius: 49,
    orbitSpeed: 0.03,
    hasRing: false,
    hasAtmosphere: true,
    atmosphereColor: "#26c6da",
    moons: 2,
    tilt: 0.1,
    content: {
      title: "TRAINING RECORDS",
      items: [
        "BTech in Computer Science and Engineering- IIIT Kalyani 2029",
        "XIIth Grade - M.H. High school and Jr college, Thane",
        "Xth Grade - Saraswati Vidyalaya, Airoli",
      ],
    },
  },

  {
    id: "photography",
    name: "Photography",
    description: "Visual captures from my lens",
    color: "#e040fb",
    emissive: "#7b1fa2",
    size: 1.3,
    orbitRadius: 42,
    orbitSpeed: 0.04,
    hasRing: true,
    ringColor: "#ce93d8",
    hasAtmosphere: true,
    atmosphereColor: "#e040fb",
    moons: 1,
    tilt: 0.25,
    isGallery: true,
    content: {
      title: "PHOTO GALLERY",
      items: [
        "Urban Architecture ",
        "Night Sky Astrophotography",
        "Street Life ",
        "Sunsets",
        "Landscape Panoramas",
        "Vehicles shot,",
      ],
    },
    gallery: [
      { title: "City at Dawn", desc: "Golden hour over the metropolitan skyline", image: "public/photos/1(1).jpg" },
      { title: "Milky Way Core", desc: "Long exposure from a remote mountain peak", image: "/photos/1(43).jpg" },
      { title: "Rainy Streets", desc: "Neon reflections on wet urban pavement", image: "/photos/1(10).jpg" },
      { title: "Dewdrop Cosmos", desc: "Macro shot of morning dew on a spider web", image: "/photos/1(11).jpg" },
      { title: "Frozen Lake", desc: "Aerial view of geometric ice patterns", image: "/photos/1(12).jpg" },
      { title: "Light Trails", desc: "Long exposure of city traffic at night", image: "/photos/1(13).jpg" },
    ],
  },
  {
    id: "contact",
    name: "Contact",
    description: "Communication uplink",
    color: "#00ff88",
    emissive: "#008844",
    size: 0.8,
    orbitRadius: 55,
    orbitSpeed: 0.025,
    hasRing: false,
    hasAtmosphere: true,
    atmosphereColor: "#00ff88",
    moons: 0,
    tilt: 0.3,
    content: {
      title: "COMM LINK",
      items: [
        "link:Email:mailto:hello@spaceportfolio.dev",
        "link:GitHub:https://github.com/cosmicdev",
        "link:LinkedIn:https://linkedin.com/in/cosmicdev",
        "link:Twitter:https://twitter.com/cosmicdev",
      ],
    },
  },
]
