import type { PlanetData } from "./planet"

export const PLANETS: PlanetData[] = [
  {
    id: "skills",
    name: "Skills",
    description: "Technical expertise & capabilities",
    color: "#00c8dc",
    emissive: "#006878",
    size: 1.5,
    orbitRadius: 12,
    orbitSpeed: 0.15,
    hasRing: false,
    hasAtmosphere: true,
    atmosphereColor: "#00c8dc",
    moons: 1,
    content: {
      title: "SKILLS MATRIX",
      items: [
        "React / Next.js / TypeScript",
        "Three.js / WebGL / GLSL",
        "Node.js / Python / Go",
        "System Design & Architecture",
        "Cloud Infrastructure (AWS/GCP)",
        "UI/UX Design & Prototyping",
      ],
    },
  },
  {
    id: "projects",
    name: "Projects",
    description: "Featured missions & deployments",
    color: "#ff6600",
    emissive: "#993300",
    size: 2,
    orbitRadius: 20,
    orbitSpeed: 0.1,
    hasRing: true,
    ringColor: "#ff8844",
    hasAtmosphere: true,
    atmosphereColor: "#ff6600",
    moons: 2,
    content: {
      title: "MISSION LOG",
      items: [
        "Nebula Dashboard - Real-time analytics platform",
        "Quantum CMS - Headless content management",
        "Stellar UI - Open-source component library",
        "Dark Matter API - High-performance REST API",
        "Pulsar Chat - Real-time messaging system",
      ],
    },
  },
  {
    id: "experience",
    name: "Experience",
    description: "Career trajectory & history",
    color: "#8ecae6",
    emissive: "#4a6a7a",
    size: 1.2,
    orbitRadius: 28,
    orbitSpeed: 0.07,
    hasRing: false,
    hasAtmosphere: true,
    atmosphereColor: "#8ecae6",
    moons: 0,
    content: {
      title: "FLIGHT LOG",
      items: [
        "Senior Engineer @ TechCorp (2023-Present)",
        "Full Stack Developer @ StartupX (2021-2023)",
        "Frontend Developer @ DesignCo (2019-2021)",
        "BS Computer Science - MIT (2019)",
      ],
    },
  },
  {
    id: "achievements",
    name: "Achievements",
    description: "Awards & milestones",
    color: "#ffcc00",
    emissive: "#997700",
    size: 1,
    orbitRadius: 35,
    orbitSpeed: 0.05,
    hasRing: true,
    ringColor: "#ffdd44",
    hasAtmosphere: false,
    moons: 3,
    content: {
      title: "COMMENDATIONS",
      items: [
        "Open Source Contributor of the Year 2024",
        "50K+ GitHub Stars Across Projects",
        "Speaker at ReactConf & NodeConf",
        "Published Technical Author",
        "Hackathon Champion x3",
      ],
    },
  },
  {
    id: "photography",
    name: "Photography",
    description: "Visual captures from my lens",
    color: "#e040fb",
    emissive: "#7b1fa2",
    size: 1.3,
    orbitRadius: 42,
    orbitSpeed: 0.04,
    hasRing: true,
    ringColor: "#ce93d8",
    hasAtmosphere: true,
    atmosphereColor: "#e040fb",
    moons: 1,
    isGallery: true,
    content: {
      title: "PHOTO GALLERY",
      items: [
        "Urban Architecture Series",
        "Night Sky Astrophotography",
        "Street Life Documentary",
        "Macro World Explorations",
        "Landscape Panoramas",
        "Abstract Light Studies",
      ],
    },
    gallery: [
      { title: "City at Dawn", desc: "Golden hour over the metropolitan skyline" },
      { title: "Milky Way Core", desc: "Long exposure from a remote mountain peak" },
      { title: "Rainy Streets", desc: "Neon reflections on wet urban pavement" },
      { title: "Dewdrop Cosmos", desc: "Macro shot of morning dew on a spider web" },
      { title: "Frozen Lake", desc: "Aerial view of geometric ice patterns" },
      { title: "Light Trails", desc: "Long exposure of city traffic at night" },
    ],
  },
  {
    id: "education",
    name: "Education",
    description: "Knowledge acquisition stations",
    color: "#26c6da",
    emissive: "#00838f",
    size: 0.9,
    orbitRadius: 49,
    orbitSpeed: 0.03,
    hasRing: false,
    hasAtmosphere: true,
    atmosphereColor: "#26c6da",
    moons: 2,
    content: {
      title: "TRAINING RECORDS",
      items: [
        "BS Computer Science - MIT (2019)",
        "Machine Learning Specialization - Stanford Online",
        "AWS Solutions Architect Certified",
        "Advanced React Patterns - Frontend Masters",
        "Distributed Systems - UC Berkeley",
      ],
    },
  },
  {
    id: "contact",
    name: "Contact",
    description: "Communication uplink",
    color: "#00ff88",
    emissive: "#008844",
    size: 0.8,
    orbitRadius: 55,
    orbitSpeed: 0.025,
    hasRing: false,
    hasAtmosphere: true,
    atmosphereColor: "#00ff88",
    moons: 0,
    content: {
      title: "COMM LINK",
      items: [
        "link:Email:mailto:hello@spaceportfolio.dev",
        "link:GitHub:https://github.com/cosmicdev",
        "link:LinkedIn:https://linkedin.com/in/cosmicdev",
        "link:Twitter:https://twitter.com/cosmicdev",
      ],
    },
  },
]
